services:
  server:
    build:
      context: .
      dockerfile: dockerfile
      target: prod
    ports:
      - 3001:3001
    command: sh -c "node src/scripts/migrate_tables.js && npm run start"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  redis:
    image: redis:alpine
    ports:
      - 6001:6379
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 20

  database:
    image: pgvector/pgvector:pg18-trixie
    ports:
      - 5001:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$PG_USERNAME\" -d \"$PG_DATABASE\""]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./data/postgresql:/var/lib/postgresql