services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: sh -c "node scripts/migrate_tables.js && node index.js"
    volumes:
      - ./logs:/app/logs
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  redis:
    image: redis:alpine
    ports:
      - 6001:6379
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 20

  database:
    image: pgvector/pgvector:pg18-trixie
    ports:
      - 5001:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_DB=${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$PG_USERNAME\" -d \"$PG_DATABASE\""]
      interval: 5s
      timeout: 5s
      retries: 20